### PR TITLE
handlers: Add "X-Attribute-*" header for OPTIONS `upload`

### LINKED ISSUE #187: CORS for /upload with header
## Current Behavior
Request `GET https://rest.fs.neo.org/v1/upload/<container_name>` with data and name body without headers works, but if I want to set an attributes (it will be header: `x-attribute-filepath: 123/123`) it's being blocked by browser because of "CORS Missing Allow Origin":

image

related to https://github.com/nspcc-dev/neofs-rest-gw/issues/166, https://github.com/nspcc-dev/neofs-rest-gw/issues/180

## Expected Behavior
Panel working fine.

## Steps to Reproduce
Can be reproduced with panel.fs.neo.org if you're to upload an object

## Context
panel.fs.neo.org is broken because of this.

## Regression
Yes, 0.7.2 handled this fine.

## Your Environment
* Version of the product used: 0.8.2

### PR DESCRIPTION
**Pull request by tatiana-nspcc**
Closes #187.

### CODE REVIEW

File: handlers/preflight.go [hunk 1]
```diff
@@ -112,7 +114,7 @@ func (a *RestAPI) OptionsContainerObject(ctx echo.Context, _ apiserver.Container
 // OptionsUploadContainerObject handler for the uploadContainerObject options request.
 func (a *RestAPI) OptionsUploadContainerObject(ctx echo.Context, _ apiserver.ContainerId) error {
 	ctx.Response().Header().Set(accessControlAllowOriginHeader, allOrigins)
-	ctx.Response().Header().Set(accessControlAllowHeadersHeader, allowHeaders)
+	ctx.Response().Header().Set(accessControlAllowHeadersHeader, fmt.Sprintf("%s, %s", allowHeaders, allowUploadHeader))
```
Comment (roman-khimov) [inline handlers/preflight.go:117]: `allowHeader + ", " + allowUploadHeader` would be more efficient here.

**Review by roman-khimov — COMMENTED** [review]
How it was tested?

File: handlers/preflight.go (hunk 1 above)
Comment (tatiana-nspcc) [reply handlers/preflight.go]: Fixed.

**Review by roman-khimov — APPROVED** [review]
