### PR TITLE
Use TLS protocol

### LINKED ISSUE #170: TLSListenAddress doesn't work
## Current Behavior
The option does nothing.

## Expected Behavior
It should start a TLS-enabled server.

## Possible Solution
Fix the damn thing.

## Regression
Yes, 0.7.2 worked fine wrt this.

## Your Environment
* Version of the product used: 0.8.0

### PR DESCRIPTION
**Pull request by tatiana-nspcc**
Close #170.

### CODE REVIEW

File: cmd/neofs-rest-gw/config.go [hunk 1]
```diff
@@ -415,6 +416,7 @@ type ServerConfig struct {
 	ReadTimeout   time.Duration
 	WriteTimeout  time.Duration
 
+	TLSEnabled        bool
```
Comment (smallhive) [inline cmd/neofs-rest-gw/config.go:420]: We have `EnabledListeners` option for this purpose. I consider we should decide either use `EnabledListeners` or remove it and use `TLSEnabled`

Comment (tatiana-nspcc) [reply cmd/neofs-rest-gw/config.go]: Yes, sorry, I missed that. I have removed `TLSEnabled`.

File: cmd/neofs-rest-gw/main.go [hunk 2]
```diff
@@ -103,11 +104,15 @@ func main() {
 
 	var tlsServer *http.Server
 	if useHTTPS {
+		tlsConfig := &tls.Config{
+			ClientCAs: loadCA(serverCfg.TLSCACertificate, logger),
```
Comment (roman-khimov) [inline cmd/neofs-rest-gw/main.go:108]: What if it's empty (and I expect it to be this way most of the time)?

Comment (tatiana-nspcc) [reply cmd/neofs-rest-gw/main.go]: Fixed. I also want to note that the function `caCertPool.AppendCertsFromPEM(caCert)` is used, which checks the key, and if something is wrong with the key, it won't be added to the `caCertPool`.

File: cmd/neofs-rest-gw/main.go [hunk 3]
```diff
@@ -110,6 +111,17 @@ func main() {
...
 
+		if serverCfg.TLSCACertificate != "" {
+			ca, err := loadCA(serverCfg.TLSCACertificate)
+			if err != nil {
+				logger.Fatal("reading server certificate", zap.Error(err))
+			}
+			tlsConfig := &tls.Config{
+				ClientCAs: ca,
+			}
+			tlsServer.TLSConfig = tlsConfig
```
Comment (roman-khimov) [inline cmd/neofs-rest-gw/main.go:122]: Well, can be simplified to
```
tlsServer.TLSConfig = &tls.Config{
	ClientCAs: ca,
}
```

**Review by roman-khimov — APPROVED** [review]
@smallhive

File: cmd/neofs-rest-gw/config.go [hunk 4]
```diff
@@ -428,7 +429,7 @@ type ServerConfig struct {
 }
 
 const (
-	FlagScheme           = "scheme"
+	FlagScheme           = "schemes"
```
Comment (roman-khimov) [inline cmd/neofs-rest-gw/config.go:432]: This needs some documentation in CHANGELOG, btw. "Updating from 0.8.4".

Comment (tatiana-nspcc) [reply cmd/neofs-rest-gw/config.go:432]: I revised the `tls-*` section in `config.yaml` and figured out that:
1. `tls-listen-limit` is not used. Should we remove it?
2. It was stated in "Updating from 0.7.2":
```
Notice that server.scheme setting is an array, it was not enforced in the
previous version (it worked fine with a string), but 0.8.0 will not work with
this incorrect configuration, so please check your configurations.
```
However, it worked throughout the 0.8.* versions. Moreover, the HTTP server starts regardless of the `scheme`/`schemes` parameter. If we want to add HTTPS, we can set it as `[https]` or `[http, https]`. The value of it only affects the Swagger docs. Is this OK? Or do we want to stop the HTTP server from starting if it's not intentionally configured?

File: cmd/neofs-rest-gw/main.go (hunk 3 above)
Comment (tatiana-nspcc) [reply cmd/neofs-rest-gw/main.go]: Thank you, fixed.

File: cmd/neofs-rest-gw/config.go (hunk 4 above)
Comment (roman-khimov) [reply cmd/neofs-rest-gw/config.go:432]: > tls-listen-limit is not used. Should we remove it?

No other gateway has it, let's drop for now.

> Moreover, the HTTP server starts regardless of the scheme/schemes parameter

How about dropping it completely? @smallhive

File: CHANGELOG.md [hunk 5]
```diff
@@ -4,6 +4,15 @@ This document outlines major changes between releases.
 
 ## [Unreleased]
 
+### Updating from 0.8.4
```
Comment (roman-khimov) [inline CHANGELOG.md:7]: 0.8.3! It's my mistake, we had so many 0.8.x that I started to think 0.8.4 is real. In fact it's not.

File: cmd/neofs-rest-gw/config.go (hunk 4 above)
Comment (tatiana-nspcc) [reply cmd/neofs-rest-gw/config.go:432]: > How about dropping it completely? @smallhive
> 
> external-address then would have to have the scheme in it, but it's OK
> 
> external-address: https://something.somewhere
In this case, `external-address` can be a list because the service can serve both HTTP and HTTPS. We should rename it to `external-addresses`, I assume. Also, I need to add another flag that indicates we want to serve the TLS protocol, like `tls-enabled`.

Comment (roman-khimov) [reply cmd/neofs-rest-gw/config.go:432]: > external-addresses

OK.

> tls-enabled

S3:
```
    tls:
      enabled: true
      cert_file: /path/to/cert
      key_file: /path/to/key
```
node:
```
    tls:
      enabled: true  # use TLS for a gRPC connection (min version is TLS 1.2)
      certificate: /path/to/cert  # path to TLS certificate
      key: /path/to/key  # path to TLS key

```
NeoGo:
```
// BasicService is used as a simple base for node services like Pprof, RPC or
// Prometheus monitoring.
type BasicService struct {
        Enabled bool `yaml:"Enabled"`
        // Addresses holds the list of bind addresses in the form of "address:port".
        Addresses []string `yaml:"Addresses"`
}

        // TLS describes SSL/TLS configuration.
        TLS struct {
                BasicService `yaml:",inline"`
                CertFile     string `yaml:"CertFile"`
                KeyFile      string `yaml:"KeyFile"`
        }
```
There are differences, but they're minor. REST however is radically different. But it shouldn't be. Let's make it more like S3 or node but without introducing multi-address.

File: CHANGELOG.md (hunk 5 above)
Comment (tatiana-nspcc) [reply CHANGELOG.md]: Fixed.

File: cmd/neofs-rest-gw/config.go (hunk 4 above)
Comment (tatiana-nspcc) [reply cmd/neofs-rest-gw/config.go]: Done.

Comment (tatiana-nspcc) [reply cmd/neofs-rest-gw/config.go]: Done.

**Comment by tatiana-nspcc** [comment]
I've made many changes; please conduct a thorough review again.

Additionally, I would like to point out that:
1. I did not add validation for config parameters in the `server.endpoints` as I don't see the necessity, but I can do it if needed.
2. In the HTTP server, there is an option to set parameters (`keep-alive`, `read-timeout`, `write-timeout`), but they were not previously used at server start, and I have preserved this behaviour.
3. I did not delve into parameters not related to the server and TLS, but I am concerned that possibly not everything is being used or is inaccurately reflected in `gate-configuration.md`. I recommend checking this separately and creating an issue for updating.

**Review by smallhive — APPROVED** [review]

**Review by roman-khimov — APPROVED** [review]
