### PR TITLE
Use `external-address` directly for Swagger docs

### LINKED ISSUE #217: Incorrect link for TLS-proxied setup
## Current Behavior
https://rest.fs.neo.org/v1/docs/ links to http://rest.fs.neo.org/v1/

## Expected Behavior
https://rest.fs.neo.org/v1/docs/ links to https://rest.fs.neo.org/v1/

## Possible Solution
Follow https://github.com/nspcc-dev/neofs-rest-gw/pull/200#discussion_r1576261389, make `external-address` contain complete URL.

## Steps to Reproduce
Put REST gateway behind TLS-terminating proxy like nginx, the gateway itself is `http://` only, but it's external address is `https://`

## Context
https://rest.fs.neo.org/v1/docs/

## Regression
Yeah, 0.8.3 allowed to configure this properly.

## Your Environment
* Version of the product used: 0.9.0

### PR DESCRIPTION
**Pull request by tatiana-nspcc**
Now `external-address` is used straightforwardly and independently of the TLS config.

Close #217.

### CODE REVIEW

**Review by smallhive — APPROVED** [review]

File: cmd/neofs-rest-gw/main.go [hunk 1]
```diff
@@ -65,30 +63,26 @@ func main() {
...
-				}
-			} else {
-				scheme = schemeHTTP
-			}
 			servers[i] = &openapi3.Server{
-				URL: fmt.Sprintf("%s://%s%s", scheme, endpointInfo.ExternalAddress, baseURL),
+				URL: fmt.Sprintf("%s%s", endpointInfo.ExternalAddress, baseURL),
 			}
 		} else {
 			logger.Info("Endpoint with missing external-address", zap.String("address", endpointInfo.Address))
```
Comment (roman-khimov) [inline cmd/neofs-rest-gw/main.go:70]: So we won't have any `URL` at all in this case? Or there is some default?

File: cmd/neofs-rest-gw/main.go [hunk 2]
```diff
@@ -65,30 +63,26 @@ func main() {
...
-						logger.Fatal("reading server certificate", zap.Error(err))
-					}
-					e.TLSServer.TLSConfig = &tls.Config{ClientCAs: ca}
-				}
-			} else {
-				scheme = schemeHTTP
-			}
 			servers[i] = &openapi3.Server{
-				URL: fmt.Sprintf("%s://%s%s", scheme, endpointInfo.ExternalAddress, baseURL),
+				URL: fmt.Sprintf("%s%s", endpointInfo.ExternalAddress, baseURL),
```
Comment (roman-khimov) [inline cmd/neofs-rest-gw/main.go:67]: Sample configuration needs to be updated and "updating from" needs to filled, it's a breaking change.

File: cmd/neofs-rest-gw/main.go (hunk 1 above)
Comment (tatiana-nspcc) [reply cmd/neofs-rest-gw/main.go:70]: No, we have never had it. It is required. Do we need a default one?

Comment (tatiana-nspcc) [reply cmd/neofs-rest-gw/main.go:70]: There is also documentation misleading, because we don't have default `external-address`.

Comment (tatiana-nspcc) [reply cmd/neofs-rest-gw/main.go:70]: Fixed `gate-configuration.md`.

Comment (roman-khimov) [reply cmd/neofs-rest-gw/main.go:70]: The default should be derived from the config, listen-address + tls.

Comment (tatiana-nspcc) [reply cmd/neofs-rest-gw/main.go]: Fixed,  `external-address` will be generated from `address` and `tls.enabled`, if not set.

**Review by roman-khimov — APPROVED** [review]
