### PR TITLE
Searchv2 duplicated attribute

### LINKED ISSUE #295: Searchv2 - failed to search objects: duplicated attribute
test_search_single_filter_by_custom_str_attributes

1. Upload multiple objects with same attribute set to different values, e.g.

```
{'X-Attributes': '{"str_attribute": "Aaa"}'}
...
{'X-Attributes': '{"str_attribute": "Aaabcd"}'}
...
{'X-Attributes': '{"str_attribute": "1Aaabcd2"}'}
```
2. Try to search with following request:
```
{'filters': [{'key': 'str_attribute', 'match': 'MatchStringEqual', 'value': 'Aaa'}], 
'attributes': ['str_attribute']},

```
3. Got 400 bad request:
```
response: {"message":"failed to search objects: duplicated attribute \"str_attribute\"","type":"GW"}
 status code: 400 Bad Request
```

https://rest.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/1052-1745351922/index.html#suites/0e3180b9561587482b2f1488d7674deb/440cd520591cdaa6/

https://github.com/nspcc-dev/neofs-testcases/pull/1037

### PR DESCRIPTION
**Pull request by smallhive**
Closes #295

### CODE REVIEW

File: internal/util/transformers.go [hunk 1]
```diff
@@ -405,8 +405,9 @@ func ToNativeFilters(searchFilters []apiserver.SearchFilter) (object.SearchFilte
 		case object.MatchNumLT:
 			fallthrough
 		case object.MatchNumLE:
+			var bi big.Int
 			// Filter value must be numeric.
-			if _, err = strconv.ParseInt(f.Value, 10, 64); err != nil {
+			if _, ok := bi.SetString(f.Value, 10); !ok {
```
[the remark this answers is not in the document]
Comment (smallhive) [reply internal/util/transformers.go:410]: There are no limits in gate specifications, and as I remember, the node limits cover `big.Int` range. What limits should I check?

[the remark this answers is not in the document]
Comment (roman-khimov) [reply internal/util/transformers.go:410]: `bit.Int` has no range, but we're not supporting anything larger than int256.

File: internal/util/transformers.go [hunk 2]
```diff
@@ -405,10 +405,25 @@ func ToNativeFilters(searchFilters []apiserver.SearchFilter) (object.SearchFilte
...
+				end   big.Int
+			)
 			// Filter value must be numeric.
-			if _, err = strconv.ParseInt(f.Value, 10, 64); err != nil {
+			if _, ok := bi.SetString(f.Value, 10); !ok {
 				return nil, fmt.Errorf("filter %s value %s is not numeric", f.Key, f.Value)
 			}
+
+			// -57896044618658097711785492504343953926634992332820282019728792003956564819968
+			start.Exp(big.NewInt(-2), big.NewInt(255), nil)
```
Comment (roman-khimov) [inline internal/util/transformers.go:419]: You don't want to do that for every request. These constants should be available in the package.

Comment (smallhive) [reply internal/util/transformers.go]: It makes sence, moved

File: internal/util/transformers.go [hunk 3]
```diff
@@ -15,6 +15,19 @@ import (
 	"github.com/nspcc-dev/neofs-sdk-go/session"
 )
 
+var (
+	start big.Int
+	end   big.Int
```
Comment (roman-khimov) [inline internal/util/transformers.go:20]: These are too generic names to be package-level.

**Review by roman-khimov — APPROVED** [review]
