### PR TITLE
Accept session v2 with and without lock prefixes

### LINKED ISSUE #362: Panic in bearer handler
## Current Behavior
```
1771453373627	2026-02-18T22:22:53.627Z		github.com/nspcc-dev/neofs-rest-gw/handlers/apiserver/rest-server.gen.go:1664 +0xd0e
1771453373627	2026-02-18T22:22:53.627Z	net/http.(*conn).serve(0xc001c4aab0, {0x12aca98, 0xc00032f950})
1771453373627	2026-02-18T22:22:53.627Z		net/http/server.go:1943 +0xd3
1771453373627	2026-02-18T22:22:53.627Z		github.com/nspcc-dev/neofs-rest-gw/handlers/api.go:228 +0x86
1771453373627	2026-02-18T22:22:53.627Z	panic({0xfe7820?, 0xc0000449d8?})
1771453373627	2026-02-18T22:22:53.627Z	github.com/nspcc-dev/neofs-rest-gw/handlers/apiserver.(*ServerInterfaceWrapper).NewGetByAttribute(0xc0021d6050, {0x12c7a90, 0xc0001588c0})
1771453373627	2026-02-18T22:22:53.627Z		github.com/labstack/echo/v4@v4.13.4/echo.go:581 +0x45
1771453373627	2026-02-18T22:22:53.627Z	github.com/nspcc-dev/neofs-rest-gw/handlers.getBearerAndSession({0x12c7a90, 0xc0001588c0}, 0x0, 0x0, 0x0)
1771453373627	2026-02-18T22:22:53.627Z	echo: http: panic serving 127.0.0.1:34268: runtime error: slice bounds out of range [:32] with capacity 15
1771453373627	2026-02-18T22:22:53.627Z		net/http/server.go:3340 +0x8e
1771453373627	2026-02-18T22:22:53.627Z	github.com/nspcc-dev/neofs-rest-gw/handlers.getSessionTokenV2({0xc00216d107?, 0xc0001588c0?})
1771453373627	2026-02-18T22:22:53.627Z		github.com/nspcc-dev/neofs-rest-gw/handlers/newObjects.go:241 +0x513
1771453373627	2026-02-18T22:22:53.627Z	net/http.(*conn).serve.func1()
1771453373627	2026-02-18T22:22:53.627Z	github.com/nspcc-dev/neofs-rest-gw/handlers.(*RestAPI).NewGetByAttribute(0xc0003307e0, {0x12c7a90, 0xc0001588c0}, {0xc00012be90, 0x2c}, {0xc00012beca, 0x8}, {0xc00012bed3, 0x19}, {0x0, ...})
1771453373627	2026-02-18T22:22:53.627Z	created by net/http.(*Server).Serve in goroutine 136
1771453373627	2026-02-18T22:22:53.627Z	github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc001ddd208, {0x12aad80, 0xc000e604b0}, 0xc000e1c780)
1771453373627	2026-02-18T22:22:53.627Z		net/http/server.go:3493 +0x485
1771453373627	2026-02-18T22:22:53.627Z	goroutine 981493 [running]:
1771453373627	2026-02-18T22:22:53.627Z	net/http.serverHandler.ServeHTTP({0xc000eb4c00?}, {0x12aad80?, 0xc000e604b0?}, 0x1?)
1771453373627	2026-02-18T22:22:53.627Z		github.com/labstack/echo/v4@v4.13.4/echo.go:668 +0x32b
1771453373627	2026-02-18T22:22:53.627Z	github.com/labstack/echo/v4.(*Echo).add.func1({0x12c7a90, 0xc0001588c0})
1771453373627	2026-02-18T22:22:53.627Z		net/http/server.go:2109 +0x665
1771453373627	2026-02-18T22:22:53.627Z		runtime/panic.go:783 +0x132
1771453373627	2026-02-18T22:22:53.627Z		github.com/nspcc-dev/neofs-rest-gw/handlers/util.go:430 +0x31b
1771453373742	2026-02-18T22:22:53.742Z	github.com/labstack/echo/v4.(*Echo).add.func1({0x12c7a90, 0xc001cbe140})
1771453373742	2026-02-18T22:22:53.742Z	net/http.(*conn).serve(0xc001fd6240, {0x12aca98, 0xc0001f3380})
1771453373742	2026-02-18T22:22:53.742Z	echo: http: panic serving 127.0.0.1:51122: runtime error: slice bounds out of range [:32] with capacity 15
1771453373742	2026-02-18T22:22:53.742Z		github.com/labstack/echo/v4@v4.13.4/echo.go:581 +0x45
1771453373742	2026-02-18T22:22:53.742Z		github.com/labstack/echo/v4@v4.13.4/echo.go:668 +0x32b
1771453373742	2026-02-18T22:22:53.742Z	github.com/nspcc-dev/neofs-rest-gw/handlers.(*RestAPI).NewGetByAttribute(0xc000392870, {0x12c7a90, 0xc001cbe140}, {0xc000135410, 0x2c}, {0xc00013544a, 0x8}, {0xc000135453, 0x19}, {0x0, ...})
1771453373742	2026-02-18T22:22:53.742Z		github.com/nspcc-dev/neofs-rest-gw/handlers/util.go:430 +0x31b
1771453373742	2026-02-18T22:22:53.742Z	github.com/nspcc-dev/neofs-rest-gw/handlers.getBearerAndSession({0x12c7a90, 0xc001cbe140}, 0x0, 0x0, 0x0)
1771453373742	2026-02-18T22:22:53.742Z		net/http/server.go:3493 +0x485
1771453373742	2026-02-18T22:22:53.742Z		github.com/nspcc-dev/neofs-rest-gw/handlers/newObjects.go:241 +0x513
1771453373742	2026-02-18T22:22:53.742Z		github.com/nspcc-dev/neofs-rest-gw/handlers/apiserver/rest-server.gen.go:1664 +0xd0e
1771453373742	2026-02-18T22:22:53.742Z		net/http/server.go:1943 +0xd3
1771453373742	2026-02-18T22:22:53.742Z		net/http/server.go:2109 +0x665
1771453373742	2026-02-18T22:22:53.742Z	github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0003ff688, {0x12aad80, 0xc000f0a0f0}, 0xc001412140)
1771453373742	2026-02-18T22:22:53.742Z		net/http/server.go:3340 +0x8e
1771453373742	2026-02-18T22:22:53.742Z	panic({0xfe7820?, 0xc000044270?})
1771453373742	2026-02-18T22:22:53.742Z	net/http.(*conn).serve.func1()
1771453373742	2026-02-18T22:22:53.742Z	net/http.serverHandler.ServeHTTP({0xc000f44200?}, {0x12aad80?, 0xc000f0a0f0?}, 0x1?)
1771453373742	2026-02-18T22:22:53.742Z	created by net/http.(*Server).Serve in goroutine 79
1771453373742	2026-02-18T22:22:53.742Z		runtime/panic.go:783 +0x132
1771453373742	2026-02-18T22:22:53.742Z	github.com/nspcc-dev/neofs-rest-gw/handlers/apiserver.(*ServerInterfaceWrapper).NewGetByAttribute(0xc0021fda90, {0x12c7a90, 0xc001cbe140})
1771453373742	2026-02-18T22:22:53.742Z	goroutine 976734 [running]:
1771453373742	2026-02-18T22:22:53.742Z		github.com/nspcc-dev/neofs-rest-gw/handlers/api.go:228 +0x86
1771453373742	2026-02-18T22:22:53.742Z	github.com/nspcc-dev/neofs-rest-gw/handlers.getSessionTokenV2({0xc0002365a7?, 0xc001cbe140?})
1771453374358	2026-02-18T22:22:54.358Z		github.com/labstack/echo/v4@v4.13.4/echo.go:581 +0x45
1771453374358	2026-02-18T22:22:54.358Z		github.com/nspcc-dev/neofs-rest-gw/handlers/apiserver/rest-server.gen.go:1664 +0xd0e
1771453374358	2026-02-18T22:22:54.358Z	net/http.(*conn).serve(0xc001e5cb40, {0x12aca98, 0xc002355680})
1771453374358	2026-02-18T22:22:54.358Z	goroutine 959593 [running]:
1771453374358	2026-02-18T22:22:54.358Z	github.com/nspcc-dev/neofs-rest-gw/handlers/apiserver.(*ServerInterfaceWrapper).NewGetByAttribute(0xc0021efed0, {0x12c7a90, 0xc001e78aa0})
1771453374358	2026-02-18T22:22:54.358Z	github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc00216e6c8, {0x12aad80, 0xc0011092c0}, 0xc001165180)
1771453374358	2026-02-18T22:22:54.358Z		net/http/server.go:1943 +0xd3
1771453374358	2026-02-18T22:22:54.358Z	github.com/nspcc-dev/neofs-rest-gw/handlers.getSessionTokenV2({0xc0020c8c27?, 0xc001e78aa0?})
1771453374358	2026-02-18T22:22:54.358Z		net/http/server.go:3493 +0x485
1771453374358	2026-02-18T22:22:54.358Z		github.com/nspcc-dev/neofs-rest-gw/handlers/newObjects.go:241 +0x513
1771453374358	2026-02-18T22:22:54.358Z	github.com/nspcc-dev/neofs-rest-gw/handlers.(*RestAPI).NewGetByAttribute(0xc0002e3cb0, {0x12c7a90, 0xc001e78aa0}, {0xc0017d2910, 0x2c}, {0xc0017d294a, 0x8}, {0xc0017d2953, 0x19}, {0x0, ...})
1771453374358	2026-02-18T22:22:54.358Z		github.com/nspcc-dev/neofs-rest-gw/handlers/api.go:228 +0x86
1771453374358	2026-02-18T22:22:54.358Z	github.com/labstack/echo/v4.(*Echo).add.func1({0x12c7a90, 0xc001e78aa0})
1771453374358	2026-02-18T22:22:54.358Z		github.com/nspcc-dev/neofs-rest-gw/handlers/util.go:430 +0x31b
1771453374358	2026-02-18T22:22:54.358Z		net/http/server.go:2109 +0x665
1771453374358	2026-02-18T22:22:54.358Z		github.com/labstack/echo/v4@v4.13.4/echo.go:668 +0x32b
1771453374358	2026-02-18T22:22:54.358Z	net/http.serverHandler.ServeHTTP({0xc001154580?}, {0x12aad80?, 0xc0011092c0?}, 0x1?)
1771453374358	2026-02-18T22:22:54.358Z	net/http.(*conn).serve.func1()
1771453374358	2026-02-18T22:22:54.358Z	panic({0xfe7820?, 0xc001da4888?})
1771453374358	2026-02-18T22:22:54.358Z		net/http/server.go:3340 +0x8e
1771453374358	2026-02-18T22:22:54.358Z	echo: http: panic serving 127.0.0.1:54950: runtime error: slice bounds out of range [:32] with capacity 15
1771453374358	2026-02-18T22:22:54.358Z		runtime/panic.go:783 +0x132
1771453374358	2026-02-18T22:22:54.358Z	created by net/http.(*Server).Serve in goroutine 137
1771453374358	2026-02-18T22:22:54.358Z	github.com/nspcc-dev/neofs-rest-gw/handlers.getBearerAndSession({0x12c7a90, 0xc001e78aa0}, 0x0, 0x0, 0x0)
1771453374987	2026-02-18T22:22:54.987Z		github.com/labstack/echo/v4@v4.13.4/echo.go:581 +0x45
1771453374987	2026-02-18T22:22:54.987Z		github.com/nspcc-dev/neofs-rest-gw/handlers/apiserver/rest-server.gen.go:1664 +0xd0e
1771453374987	2026-02-18T22:22:54.987Z	net/http.(*conn).serve(0xc001a40900, {0x12aca98, 0xc001fd7560})
1771453374987	2026-02-18T22:22:54.987Z	goroutine 956886 [running]:
1771453374987	2026-02-18T22:22:54.987Z	github.com/nspcc-dev/neofs-rest-gw/handlers/apiserver.(*ServerInterfaceWrapper).NewGetByAttribute(0xc001e1b500, {0x12c7a90, 0xc00179b7c0})
1771453374987	2026-02-18T22:22:54.987Z	github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc001aaafc8, {0x12aad80, 0xc0004681e0}, 0xc000cec780)
1771453374987	2026-02-18T22:22:54.987Z		net/http/server.go:1943 +0xd3
1771453374987	2026-02-18T22:22:54.987Z	github.com/nspcc-dev/neofs-rest-gw/handlers.getSessionTokenV2({0xc001b0d8c7?, 0xc00179b7c0?})
1771453374987	2026-02-18T22:22:54.987Z		net/http/server.go:3493 +0x485
1771453374987	2026-02-18T22:22:54.987Z		github.com/nspcc-dev/neofs-rest-gw/handlers/newObjects.go:241 +0x513
1771453374987	2026-02-18T22:22:54.987Z	github.com/nspcc-dev/neofs-rest-gw/handlers.(*RestAPI).NewGetByAttribute(0xc0002ad5f0, {0x12c7a90, 0xc00179b7c0}, {0xc00109fa90, 0x2c}, {0xc00109faca, 0x8}, {0xc00109fad3, 0x19}, {0x0, ...})
1771453374987	2026-02-18T22:22:54.987Z		github.com/nspcc-dev/neofs-rest-gw/handlers/api.go:228 +0x86
1771453374987	2026-02-18T22:22:54.987Z	github.com/labstack/echo/v4.(*Echo).add.func1({0x12c7a90, 0xc00179b7c0})
1771453374987	2026-02-18T22:22:54.987Z		github.com/nspcc-dev/neofs-rest-gw/handlers/util.go:430 +0x31b
1771453374987	2026-02-18T22:22:54.987Z		net/http/server.go:2109 +0x665
1771453374987	2026-02-18T22:22:54.987Z		github.com/labstack/echo/v4@v4.13.4/echo.go:668 +0x32b
1771453374987	2026-02-18T22:22:54.987Z	net/http.serverHandler.ServeHTTP({0xc0015b1500?}, {0x12aad80?, 0xc0004681e0?}, 0x1?)
1771453374987	2026-02-18T22:22:54.987Z	net/http.(*conn).serve.func1()
1771453374987	2026-02-18T22:22:54.987Z	panic({0xfe7820?, 0xc001da4858?})
1771453374987	2026-02-18T22:22:54.987Z		net/http/server.go:3340 +0x8e
1771453374987	2026-02-18T22:22:54.987Z	echo: http: panic serving 127.0.0.1:47518: runtime error: slice bounds out of range [:32] with capacity 15
1771453374987	2026-02-18T22:22:54.987Z		runtime/panic.go:783 +0x132
1771453374987	2026-02-18T22:22:54.987Z	created by net/http.(*Server).Serve in goroutine 131
1771453374987	2026-02-18T22:22:54.987Z	github.com/nspcc-dev/neofs-rest-gw/handlers.getBearerAndSession({0x12c7a90, 0xc00179b7c0}, 0x0, 0x0, 0x0)
```

## Expected Behavior
No panic.

## Possible Solution
Fix something.

## Steps to Reproduce
Unknown.

## Context
Happened in testnet.

## Regression
Unknown.

## Your Environment
* Version of the product used: 0.16.0

### PR DESCRIPTION
**Pull request by smallhive**
Closes #362.

### CODE REVIEW

File: handlers/util.go [hunk 1]
```diff
@@ -427,16 +427,47 @@ func getSessionTokenV2(v string) (*sessionv2.Token, error) {
 		return nil, fmt.Errorf("base64 encoding: %w", err)
 	}
 
+	// Try parsing without lock prefix first.
+	st, err := parseTokenWithoutLock(tokenBts)
+	if err == nil {
+		return st, nil
```
Comment (roman-khimov) [inline handlers/util.go]: This shouldn't work. Lock isn't optional, it's mandatory.

Comment (smallhive) [reply handlers/util.go]: Ok
