### PR TITLE
Remove doubled JSON response

### LINKED ISSUE #265: Gateway responds with two JSONs in case of error
## Current Behavior
Object put reply:
```
{"code":2048,"message":"writer close: status: code = 2048 message = access to object operation denied","type":"API"}
{"container_id":"754iyTDY8xUtZJZfheSYLUn7jvCkxr79RcbjMt81QykC","object_id":"11111111111111111111111111111111"}
```

## Expected Behavior
A single JSON struct with error (it fails at the NeoFS level), second JSON is misleading and can make applications think the operation is successful where it's not.

## Possible Solution
Drop the second output line.

## Steps to Reproduce
Upload to a container without appropriate rights via REST.

## Context
Affects send.fs.neo.org.

## Regression
Unknown, maybe.

## Your Environment
* Version of the product used: 0.11.1
* Server setup and configuration files used: testnet
* Operating System and version (`uname -a`): Debian stable

### PR DESCRIPTION
**Pull request by smallhive**
Closes #265.

### CODE REVIEW

File: handlers/util.go [hunk 1]
```diff
@@ -412,19 +412,16 @@ func (a *RestAPI) putObject(ctx echo.Context, hdr object.Object, bt *bearer.Toke
...
 	if err != nil {
-		resp := a.logAndGetErrorResponse("write", err)
-		return oid.ID{}, ctx.JSON(http.StatusBadRequest, resp)
+		return oid.ID{}, fmt.Errorf("write: %w", err)
 	}
 
 	if err = writer.Close(); err != nil {
-		resp := a.logAndGetErrorResponse("writer close", err)
-		return oid.ID{}, ctx.JSON(http.StatusBadRequest, resp)
+		return oid.ID{}, fmt.Errorf("writer cloe: %w", err)
```
Comment (tatiana-nspcc) [inline handlers/util.go:424]: "close"

**Review by tatiana-nspcc — CHANGES_REQUESTED** [review]

**Comment by smallhive** [comment]
I looked at the code, I don't see other places for such behaviour. There are two similar places with `ctx.JSON` not in the handlers: `headByAddress` and `getByAddress`. But their results immediately returns from handlers, there is not possible to have double output

**Review by tatiana-nspcc — APPROVED** [review]

**Review by roman-khimov — APPROVED** [review]
