### PR TITLE
Token reuse

### LINKED ISSUE #349: Token reuse issue
## Current Behavior
Get a session token from somewhere (transaction, object), pass it into a request to appropriate gateway --- do whatever is allowed by this token. It's a big problem for public gateways.

## Expected Behavior
Token alone is insufficient for valid requests to REST.

## Possible Solution
REST is somewhat special, it needs some additional data to bind token to its real owner. This can be done if request contains something that only owner knows. Proving this shouldn't require any server-level state, so we need some data embedded into token itself that can be linked to data outside of the token. That's exactly what https://github.com/nspcc-dev/neofs-api/pull/378 provides.

My proposal is for a simple hash lock, we put a hash of some random string to the token and then this string is passed along with the token for every request. To achieve this:
 * extend SessionTokenv2Response with `lock` field
 * generate a (32 byte) string, put its hash into token and the string to this returned `lock`
 * accept `lock` in `/v2/auth/session/complete`, check it, create a token then prepend this `lock` to it, return a string to client
 * upon receival, decode, extract `lock` (fixed size, easy), unpack session token, check that `lock` hashes to value inside the token
 * drop session token v1 support completely everywhere (breaking change, but there is no alternative)

Other schemes can be considered, but this one seems to be sufficient given the nature of HTTP Bearer authorization.

## Regression
Nope, this problem existed since the first commits to REST in 2022. But v2 tokens allowed to discover it.

### PR DESCRIPTION
**Pull request by smallhive**
Closes #349

### CODE REVIEW

File: handlers/containers.go [hunk 1]
```diff
@@ -472,9 +438,7 @@ func createContainer(ctx context.Context, p *waiter.Waiter, stoken *session.Cont
 	cnr.SetPlacementPolicy(policy)
 	cnr.SetBasicACL(basicACL)
 
-	if stoken != nil {
-		cnr.SetOwner(stoken.Issuer())
-	} else if sessionTokenV2 != nil {
+	if sessionTokenV2 != nil {
```
Comment (roman-khimov) [inline handlers/containers.go]: Can it really be `nil`?

**Review by roman-khimov — APPROVED** [review]
Docs still missing, add it ASAP. Merging to start test adaptation.
