### PR TITLE
Skip cancelled context

### LINKED ISSUE #377: v0.16.0 stopped with error:
```
systemd[1]: Stopping neofs-rest.service - NeoFS REST Gateway...
neofs-rest-gw[761]: info        metrics/service.go:40        shutting down service        {"service": "Prometheus", "endpoint": "localhost:9941"}
neofs-rest-gw[761]: info        metrics/service.go:40        shutting down service        {"service": "Pprof", "endpoint": "localhost:9942"}
neofs-rest-gw[761]: fatal        neofs-rest-gw/main.go:132        shutdown http and https        {"error": "context canceled"}
neofs-rest-gw[761]: main.main
neofs-rest-gw[761]:         github.com/nspcc-dev/neofs-rest-gw/cmd/neofs-rest-gw/main.go:132
neofs-rest-gw[761]: runtime.main
neofs-rest-gw[761]:         runtime/proc.go:285
systemd[1]: neofs-rest.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: neofs-rest.service: Failed with result 'exit-code'.
systemd[1]: Stopped neofs-rest.service - NeoFS REST Gateway.
systemd[1]: neofs-rest.service: Consumed 1h 53min 1.383s CPU time, 161.6M memory peak, 53.3M memory swap peak.
systemd[1]: Started neofs-rest.service - NeoFS REST Gateway.
```

### PR DESCRIPTION
**Pull request by smallhive**
Closes #377

### CODE REVIEW

File: cmd/neofs-rest-gw/main.go [hunk 1]
```diff
@@ -128,7 +129,15 @@ func main() {
 
 	<-ctx.Done()
 	neofsAPI.StopServices()
-	if err = e.Shutdown(ctx); err != nil {
+
+	stopCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
+	defer cancel()
+
+	if err = e.Shutdown(stopCtx); err != nil {
+		if errors.Is(err, context.Canceled) {
```
Comment (roman-khimov) [inline cmd/neofs-rest-gw/main.go:132]: If it's a new context then cancellation is abnormal, I think. Old one is dead, OK, but new one should finish normally.

Comment (smallhive) [reply cmd/neofs-rest-gw/main.go:132]: I don't mind, updated

Comment (roman-khimov) [reply cmd/neofs-rest-gw/main.go:132]: This doesn't make sense now. We know for sure `ctx` is dead, so it'll _always_ be `context.Canceled`.

Comment (smallhive) [reply cmd/neofs-rest-gw/main.go:132]: Not exactly, locally I tried to stop the gate, and it stopped without any `context.Canceled`. Maybe the issue case had some special kill or another condition

Comment (roman-khimov) [reply cmd/neofs-rest-gw/main.go:132]: It's certainly SIGTERM, please check that.

Comment (smallhive) [reply cmd/neofs-rest-gw/main.go:132]:
```shell
...
2026-04-15T07:30:53.705+0400    info    neofs-rest-gw/main.go:107       starting server {"address": "localhost:8081"}
2026-04-15T07:30:53.705+0400    info    metrics/service.go:28   service is running      {"service": "Prometheus", "endpoint": "localhost:8092"}
2026-04-15T07:30:53.705+0400    info    metrics/service.go:28   service is running      {"service": "Pprof", "endpoint": "localhost:8091"}
⇨ http server started on 127.0.0.1:8081
```
```shell
kill -15 20140
```
```shell
2026-04-15T07:31:28.218+0400    info    metrics/service.go:40   shutting down service   {"service": "Pprof", "endpoint": "localhost:8091"}
2026-04-15T07:31:28.218+0400    info    metrics/service.go:40   shutting down service   {"service": "Prometheus", "endpoint": "localhost:8092"}
```
Checked both `syscall.SIGINT` and `syscall.SIGTERM`.
Additionally, I added a separate log for `errors.Is(err, context.Canceled)` section and it wasn't printed

Comment (roman-khimov) [reply cmd/neofs-rest-gw/main.go:132]: Still not sure it's correct, but anyway.

**Review by roman-khimov — APPROVED** [review]
