### PR TITLE
Handle incomplete search result

### LINKED ISSUE #329: handle incomplete search result
```
neofs-rest-gw: error        handlers/api.go:144        could not search for objects
```

```Json
{
  "handler": "NewGetByAttribute",
  "containerID": "5Feinb2PaGFqdzviYfodCRMKd4j49Rtey3rSGqGhX8wn",
  "attrKey": "FilePath",
  "attrVal": "index.html",
  "error": "search: status: code = 1 message = last error: all 03933279423bf3504b61f76912790a566d99929eb047f30c8699f8e49a34ab07f7 endpoints failed, first error: /dns4/minerva.nspcc.ru/tcp/8080: send request over gRPC: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 51.77.119.31:8080: i/o timeout\""
}
```

### PR DESCRIPTION
**Pull request by smallhive**
Closes #329

### CODE REVIEW

File: handlers/objects.go [hunk 1]
```diff
@@ -351,6 +364,7 @@ func (a *RestAPI) V2SearchObjects(ctx echo.Context, containerID apiserver.Contai
 	}
 
 	ctx.Response().Header().Set(accessControlAllowOriginHeader, "*")
+	ctx.Response().Header().Set(xIncompleteHeader, strconv.FormatBool(incomplete))
```
Comment (roman-khimov) [inline handlers/objects.go]: Why a header? You can have it as a part of `ObjectListV2` structure. And not add it if it's false (most of the time).

File: handlers/objects.go [hunk 2]
```diff
@@ -240,6 +246,7 @@ func (a *RestAPI) SearchObjects(ctx echo.Context, containerID apiserver.Containe
...
```
Comment (roman-khimov) [inline handlers/objects.go]: v1 can be left as is, users should suffer a bit with it.

Comment (smallhive) [reply handlers/objects.go]: Nice, reverted

File: CHANGELOG.md [hunk 3]
```diff
@@ -5,6 +5,7 @@ This document outlines major changes between releases.
 ## [Unreleased]
 
 ### Added
+- Incomplete flag `/v2/objects/{cid}/search` operation (#329)
```
Comment (roman-khimov) [inline CHANGELOG.md]: incomplete flag to or for

File: spec/rest.yaml [hunk 4]
```diff
@@ -1615,6 +1615,9 @@ components:
         cursor:
           description: Value to start the next batch from.
           type: string
+        incomplete:
+          description: If true, it describes incomplete success. The search has been done, but the result can't be considered completely fine.
```
[the remark this answers is not in the document]
Comment (smallhive) [reply spec/rest.yaml]: Updated
